name: Go Test

on:
  push:

jobs:
  test:
    name: Unit test
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.2
      - name: Install gomock
        run: go install go.uber.org/mock/mockgen@latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build mocks
        run: |
          ci/mocks.sh
      - name: Vet
        run: |
          go vet ./...
      - name: Test
        run: go test -race -v ./...