name: Go Test

on:
  push:

jobs:
  test:
    name: Unit test
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.4
      - name: Install gomock
        run: go install go.uber.org/mock/mockgen@latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build mocks
        run: |
          ci/mocks.sh
      - name: Vet
        run: |
          go vet ./...
      - name: Test
        run: go test -race -v ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.4.0
        with:
          # The action will automatically pick up .golangci.yml from the repo root
          # You can customize flags if needed. Keeping defaults here.
          version: latest
          args: --timeout=5m
